#!/bin/bash
MUSIC_FOLDER="/home/suseika/Music"
PIPEFILE=~/.musicpipe # A named pipe to communicate with mplayer in slave mode
if [ "$1" == "--pause" ] && [ "$#" == "1" ];
then
	# When ran with a single --pause argument, pause currently running player
	echo pause > $PIPEFILE &
	exit
elif [ "$1" != "" ];
then
	QUERY="$@" # All arguments
else
	QUERY=`zenity --entry` # When run with arguments other than a single "pause", read query from 
	set -- $QUERY
fi
if [ "$QUERY" == "" ];
then
	exit
fi
killall mplayer --quiet # terminate previously running mplayers

locate -i $QUERY \
	| grep -i "$1" \
	| grep -i "$2" \
	| grep -i "$3" \
	| grep -i "$4" \
	| grep -i "$5" \
	| grep -i "$6" \
	| grep -i "$7" \
	| grep -i "$8" \
	| grep -i "$9" \
	| grep -Ei "(flac|ape|mp3|wav|wv|m4a)$" \
	| grep "$MUSIC_FOLDER" \
	| pee 'xargs -d"\n" -I{} basename -a "{}" | naughtify>/dev/null' cat \
	| sed 's/^/loadfile "/' \
	| sed 's/$/" 1/' \
	| mplayer --idle -slave -input file=$PIPEFILE


